### ISSUE TITLE
Moqups

### ISSUE THREAD

**Issue by pro2847** [opensourcewebsite-org/opensourcewebsite-org#2]
- [x] html for moqups page

- [x] In the left menu, delete the Moqup preview and Moqup edit pages after they are used on the Moqups page. On the Moqups page, the All and Your tabs should be made to separate pages. | В левом меню удалить страницы Moqup preview и Moqup edit после того как они будут использованы на странице Moqups. На странице Moqups - вкладки All и Your должны быть сделаны отдельными страницами. 

- [x] In the database, create the Setting table. This table stores dynamic site parameters. Add two parameters to it: 1. the total maximum number of html and css entries allowed for one rating unit per user. empty css entries are not considered. the default is 20 entries for one rating. 2. The total size in bytes of all html and css entries for one rating unit per user. the default is 1mb. | В базе данных создать таблицу Setting. В этой таблице хранятся динамические параметры сайта. Добавить в нее два параметра: 1. общее максимальное количество записей html и css разрешенных для одной единицы рейтинга одного пользователя. пустые записи css не считаются. по умолчанию 20 записей для одного рейтинга. 2. общий размер в байтах всех записей html и css для одной единицы рейтинга одного пользователя. по умолчанию 1mb.

- [x] In editing / creating Moqup. The html field is required, the css field is optional. The maximum size of each field is 100,000 characters. Cut JS code and connect JS scripts. css is stored separately from html, since in the future one html record can have several css entries. | В редактировании/создании Moqup. Поле html обязательное, поле css необязательное. Максимальный размер каждого поля 100000 символов. Вырезать JS код и подключение JS скриптов. css хранить отдельно от html, так как в будущем у одной html записи может быть несколько css записей.

- [x] In the Moqups list - all entries are available to other users. | В просмотре записей Moqups - все записи доступны другим пользователям.

**Comment by pro2847** [comment]
Bug. After save a new moqup

View not Found – yii\base\ViewNotFoundException

The view file does not exist: /views/site/design-list.php

**Comment by pro2847** [comment]
Bug. Delete for own moqups dont click and dont work. Make a standard confirmation message in the browser when a user try to delete it.

**Comment by sapkaljagruti** [comment]
Bug. Delete for own moqups dont click and dont work. Make a standard confirmation message in the browser when a user try to delete it.
==> Delete is not in the task list, even creating neew controller is also, 

Bug. After save a new moqup

View not Found – yii\base\ViewNotFoundException

The view file does not exist: /views/site/design-list.php

=> this bug have been fixed and commited, and that too without tracker, don't worry. please check.

**Comment by pro2847** [comment]
Bug. /moqup/design-add this page available for guests now
