### ISSUE TITLE
yii\base\ErrorException: Trying to get property 'key' of non-object in /www/opensourcewebsite.org/htdocs/views/setting/setting-values.php:9

### ISSUE THREAD

**Issue by grandmotivator** [opensourcewebsite-org/opensourcewebsite-org#229]
https://opensourcewebsite.org/setting/values?id=100000

[error][yii\base\ErrorException:8]
yii\base\ErrorException: Trying to get property 'key' of non-object in
/www/opensourcewebsite.org/htdocs/views/setting/setting-values.php:9
Stack trace:
#0
/www/opensourcewebsite.org/htdocs/views/setting/setting-values.php(9):
yii\base\ErrorHandler->handleError(8, 'Trying to get p...',
'/www/opensource...', 9, Array)
#1
/www/opensourcewebsite.org/htdocs/vendor/yiisoft/yii2/base/View.php(348):
require('/www/opensource...')
#2
/www/opensourcewebsite.org/htdocs/vendor/yiisoft/yii2/base/View.php(257):
yii\base\View->renderPhpFile('/www/opensource...', Array)
#3
/www/opensourcewebsite.org/htdocs/vendor/yiisoft/yii2/base/View.php(156):
yii\base\View->renderFile('/www/opensource...', Array,
Object(app\controllers\SettingController))
#4
/www/opensourcewebsite.org/htdocs/vendor/yiisoft/yii2/base/Controller.php(384):
yii\base\View->render('setting-values', Array,
Object(app\controllers\SettingController))
#5
/www/opensourcewebsite.org/htdocs/controllers/SettingController.php(80):
yii\base\Controller->render('setting-values', Array)
#6 [internal function]:
app\controllers\SettingController->actionValues('100000')
#7
/www/opensourcewebsite.org/htdocs/vendor/yiisoft/yii2/base/InlineAction.php(57):
call_user_func_array(Array, Array)
#8
/www/opensourcewebsite.org/htdocs/vendor/yiisoft/yii2/base/Controller.php(157):
yii\base\InlineAction->runWithParams(Array)
#9
/www/opensourcewebsite.org/htdocs/vendor/yiisoft/yii2/base/Module.php(528):
yii\base\Controller->runAction('values', Array)
#10
/www/opensourcewebsite.org/htdocs/vendor/yiisoft/yii2/web/Application.php(103):
yii\base\Module->runAction('setting/values', Array)
#11
/www/opensourcewebsite.org/htdocs/vendor/yiisoft/yii2/base/Application.php(386):
yii\web\Application->handleRequest(Object(yii\web\Request))
#12 /www/opensourcewebsite.org/htdocs/web/index.php(21):
yii\base\Application->run()
#13 {main}

**Comment by Loctarogar** [comment]
Ok, i downloaded project and i see the error controller sends empty variable. But how do you want to handle it? Check variable in controller and if variable is empty send to some error page or check variable in view and if variable is empty just don"t show the info ?

**Comment by grandmotivator** [comment]
404 page

**Comment by Loctarogar** [comment]
Why on localhost if i go to localhost:8080/website-settings i redirected to http://localhost:8080/account ?

**Comment by grandmotivator** [comment]
Confirm your Email
