### ISSUE TITLE
Login for users with unconfirmed emails

### ISSUE THREAD

**Issue by grandmotivator** [opensourcewebsite-org/opensourcewebsite-org#307]
When trying to enter the system for users with unconfirmed email addresses, show in the authorization form a notification (error) indicating that it is necessary to confirm the email address.

**Comment by ohDaddyPlease** [comment]
При регистрации нового пользователя происходит автоматический вход в систему без проверки подтвержденной электронной почты.
При выходе из аккаунта с неподтвержденной электронной почтой и попытке зайти снова, система не произведет вход и выбросит ошибку о необходимости подтвердить почту.
