### ISSUE TITLE
Some users have problems with registration and authorization (Bad request #400)

### ISSUE THREAD

**Issue by grandmotivator** [opensourcewebsite-org/opensourcewebsite-org#380]
`[yii\web\HttpException:400] yii\web\BadRequestHttpException: Unable to verify your data submission`

<img width="861" alt="Screenshot 2020-04-27 at 13 17 09" src="https://user-images.githubusercontent.com/34159182/80339763-8e72b280-8889-11ea-9465-e8bc2078ff48.png">

В Opera были отключены куки.

**Comment by ohDaddyPlease** [comment]
Баг возникает в Opera под VPN из России. после заполнения формы регистрации и клика по кнопке sign up.

Баг сложно отследить, поэтому необходимо при возникновении дополнить информацию о воспроизведению ошибки.
