### ISSUE TITLE
Improve requirements.php

### ISSUE THREAD

**Issue by grandmotivator** [opensourcewebsite-org/opensourcewebsite-org#400]
Добавить проверку версии mysql базы данных.

https://github.com/opensourcewebsite-org/opensourcewebsite-org/blob/master/requirements.php

**Comment by ohDaddyPlease** [comment]
для добавления новой проверки можно в переменную $requirements добавить код, например:
    'mySql' => [
        'name' => 'MySQL version check',
        'mandatory' => false,
        'condition' => //проверка - true или false. если false - проверка не прошла и будет выкинута ошибка,
        'by' => 'compatibility reasons' //указывается по какой причине происходит проверка,
        'memo' => //сообщение, которое будет выкинуто в случае неудачи
    ]

для проверки, выше $requirements, можно сделать проверку версии бд следующим образом:
$dbhost = getenv('DB_HOST');
$dbuser = getenv('DB_USERNAME');
$dbpassword = getenv('DB_PASSWORD');
$mysql_version = (new mysqli($dbhost, $dbuser, $dbpassword))->server_info; //либо server_version

**важно**:
надо понимать, что может быть установлена MariaDB или MySQL, у них разные версии.
например, у меня MariaDB версии 10 с чем-то, а MySQL в данный момент имеет версию 8. поэтому нужно продумать парсинг версии (regexp, например) в зависимости от бд
