### ISSUE TITLE
Telegram Bot. Voteban функция для групп. Подсчет количества голосов.

### ISSUE THREAD

**Issue by grandmotivator** [opensourcewebsite-org/opensourcewebsite-org#406]
Когда набирается нужное количество голосов то происходит лишнее обновление сообщения бота с голосованием, например показывает количество голосов 7/7, хотя можно было бы этого не делать и сразу удалять сообщения и банить пользователя, то же самое актуально и для спасения пользователя.

**Comment by guzich** [comment]
исправлено 
https://github.com/opensourcewebsite-org/opensourcewebsite-org/pull/412
