### ISSUE TITLE
Moqups layout update

### ISSUE THREAD

**Issue by VicD129** [opensourcewebsite-org/opensourcewebsite-org#46]
Implement changes for Moqups' layouts and develop necessary functionality.

Layouts:
- Moqups List https://opensourcewebsite.org/moqup/design-view?id=17
- Moqup Page https://opensourcewebsite.org/moqup/design-view?id=18
- Moqup Page Fork https://opensourcewebsite.org/moqup/design-view?id=19

**Comment by kronos1390** [comment]
Hello, please resolve me these doubts:
1- In view moqup, the tab code will contain the html and css unified? Or there should be both tabs, like in create?

2- When the moqup is forked, the compare tab will show the diff between the current moqup and the original, right?

3- How would be the "followed user" and "followed moqup" functionality?

**Comment by VicD129** [comment]
Hello,

1. No, put that in different tabs separately, HTML and CSS, like in Edit Mode.
2. Yes. If it possible, highlight the added/removed/updated lines.
3. You can follow the page or the User (all User's pages). All followed pages collected on "Following" tab.

**Comment by pro2847** [comment]
When fork, consider the limitation for the number and volume of moqups from one user, since in fact the user creates a moqup.

When the source moqup is removed, the fork is untied and becomes an independent moqup.
